# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SummerProject2016' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SummerProject2016
  pod ‘Firebase’
  pod ‘Firebase/Auth’
  pod ‘Bolts’
  pod ‘Firebase/Storage’
  pod ‘Firebase/Database’

  target 'SummerProject2016Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SummerProject2016UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
